services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: unipark-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: unipark
      POSTGRES_USER: unipark
      POSTGRES_PASSWORD: unipark
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./infra/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis:
    image: redis:7-alpine
    container_name: unipark-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Keycloak eliminado — autenticación migrada a Auth0 (hosted)
  # Auth0 domain: dev-5ndrp8gm0rm3r0mw.us.auth0.com

volumes:
  redis_data:


