services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: unipark-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: unipark
      POSTGRES_USER: unipark
      POSTGRES_PASSWORD: unipark
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./infra/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis:
    image: redis:7-alpine
    container_name: unipark-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: unipark-keycloak
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: unipark
      KC_DB_PASSWORD: unipark
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
    depends_on:
      - postgres
    # Para levantar solo: docker compose --profile auth up keycloak
    # URL admin: http://localhost:8080
    # Realm unipark: http://localhost:8080/realms/unipark
    profiles:
      - auth

volumes:
  redis_data:


