import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#111317",
        surface: "#111317",
        "surface-container": "#1e2024",
        "surface-container-low": "#1a1c20",
        "surface-container-lowest": "#0c0e12",
        "surface-container-high": "#282a2e",
        "surface-container-highest": "#333539",
        "surface-variant": "#333539",
        "surface-bright": "#37393e",
        "surface-dim": "#111317",
        "on-background": "#e2e2e8",
        "on-surface": "#e2e2e8",
        "on-surface-variant": "#b9cacb",
        "primary-fixed": "#7df4ff",
        "primary-fixed-dim": "#00dbe9",
        primary: "#dbfcff",
        "on-primary": "#00363a",
        "on-primary-container": "#006970",
        "primary-container": "#00f0ff",
        "inverse-primary": "#006970",
        "on-primary-fixed": "#002022",
        "on-primary-fixed-variant": "#004f54",
        "surface-tint": "#00dbe9",
        "secondary-fixed": "#36ffc4",
        "secondary-fixed-dim": "#00e1ab",
        "secondary-container": "#36ffc4",
        secondary: "#ffffff",
        "on-secondary": "#003828",
        "on-secondary-container": "#007255",
        "on-secondary-fixed": "#002116",
        "on-secondary-fixed-variant": "#00513c",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        tertiary: "#faf3ff",
        "tertiary-container": "#e1d2ff",
        "tertiary-fixed": "#e9ddff",
        "tertiary-fixed-dim": "#d1bcff",
        "on-tertiary": "#3c0090",
        "on-tertiary-container": "#7213ff",
        "on-tertiary-fixed": "#23005b",
        "on-tertiary-fixed-variant": "#5700c9",
        outline: "#849495",
        "outline-variant": "#3b494b",
        "inverse-surface": "#e2e2e8",
        "inverse-on-surface": "#2f3035",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Sora", "sans-serif"],
        sora: ["Sora", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "mono-data": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "700" }],
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        gutter: "16px",
      },
      animation: {
        "slide-up-fade": "slideUpFade 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        shimmer: "shimmerLine 2s infinite",
      },
      keyframes: {
        slideUpFade: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        shimmerLine: {
          "0%": { transform: "translateX(-150%)" },
          "100%": { transform: "translateX(150%)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
